# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Trainer(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email: str=None, phone: int=None, first_name: str=None, last_name: str=None, id: str=None):  # noqa: E501
        """Trainer - a model defined in Swagger

        :param email: The email of this Trainer.  # noqa: E501
        :type email: str
        :param phone: The phone of this Trainer.  # noqa: E501
        :type phone: int
        :param first_name: The first_name of this Trainer.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this Trainer.  # noqa: E501
        :type last_name: str
        :param id: The id of this Trainer.  # noqa: E501
        :type id: str
        """
        self.swagger_types = {
            'email': str,
            'phone': int,
            'first_name': str,
            'last_name': str,
            'id': str
        }

        self.attribute_map = {
            'email': 'email',
            'phone': 'phone',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'id': 'id'
        }
        self._email = email
        self._phone = phone
        self._first_name = first_name
        self._last_name = last_name
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Trainer':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Trainer of this Trainer.  # noqa: E501
        :rtype: Trainer
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this Trainer.


        :return: The email of this Trainer.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this Trainer.


        :param email: The email of this Trainer.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def phone(self) -> int:
        """Gets the phone of this Trainer.


        :return: The phone of this Trainer.
        :rtype: int
        """
        return self._phone

    @phone.setter
    def phone(self, phone: int):
        """Sets the phone of this Trainer.


        :param phone: The phone of this Trainer.
        :type phone: int
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone

    @property
    def first_name(self) -> str:
        """Gets the first_name of this Trainer.


        :return: The first_name of this Trainer.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this Trainer.


        :param first_name: The first_name of this Trainer.
        :type first_name: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this Trainer.


        :return: The last_name of this Trainer.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this Trainer.


        :param last_name: The last_name of this Trainer.
        :type last_name: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def id(self) -> str:
        """Gets the id of this Trainer.


        :return: The id of this Trainer.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Trainer.


        :param id: The id of this Trainer.
        :type id: str
        """

        self._id = id
